name: Test Documentation

on:
  pull_request:
    paths:
      - docs/**
      - moonwave.toml
      - .moonwave/**
      - .github/workflows/DeployDocs.yml
      - src/**
      - blog/**
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  build-docs:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install Moonwave
        run: npm i -g moonwave
      - name: Build docs site
        env:
          NODE_OPTIONS: '--no-experimental-require-module'
        run: moonwave build