name: Deploy Docs Site with Moonwave

on:
  push:
    paths:
      - docs/**
      - .moonwave/**
      - moonwave.toml
      - .github/workflows/DeployDocs.yml
      - src/**
      - blog/**
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install Moonwave
        run: npm i -g moonwave
      - name: Setup Git config
        run: |
          git config user.name "github-actions-bot"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
      - name: Build and publish docs site
        env:
          NODE_OPTIONS: '--no-experimental-require-module'
        run: moonwave build --publish